#!/usr/bin/env python2

from sys import argv
from mechanize import Browser
from os import system
pnr = argv[1]

#open browser
br = Browser()

#open page
br.open("http://www.indianrail.gov.in/pnr_Enq.html")

#select form, nr=0 because it is the only form in the page
br.select_form(nr=0)
br["lccp_pnrno1"] = pnr
br.submit()
unparsed_output = br.response().read()
system("echo '%s' | elinks --dump" %unparsed_output)
